### ISSUE TITLE
Create Functions for motor control 

### ISSUE THREAD

**Issue by issc29** [jakekali/galpBot#1]
The code right now is good but you are duplicating the same code over and over. 

Recommendation:
- [ ] Create Functions that you can call instead of duplicating code

**Comment by jakekali** [comment]
In the future, once @joebraha and I figure out which pins need to be turned on and off in order to turn, we will change it so they do different things.

Functions can still be used to clean up the code as well, with direction as parameters.

**Comment by joebraha** [comment]
Up carrot. This is a very rough draft - few modifications made to an LED Controller online
